Question:
How would you implement row-level security in Snowflake so that users only see rows from their own department, based on their assigned role?

CREATE OR REPLACE TABLE employee_data (
    emp_id INT,
    full_name STRING,
    department STRING,
    birth_date DATE,
    salary NUMBER
);

INSERT INTO employee_data VALUES
(101, 'Amit Sharma', 'HR', '1990-07-15', 50000),
(102, 'Priya Mehta', 'Finance', '1985-12-03', 75000),
(103, 'Ravi Kumar', 'IT', '1992-03-22', 90000);


CREATE OR REPLACE ROLE HR_ROLE;
CREATE OR REPLACE ROLE FINANCE_ROLE;
CREATE OR REPLACE ROLE IT_ROLE;


GRANT ROLE HR_ROLE TO USER prabhakarreddy1433;
GRANT ROLE FINANCE_ROLE TO USER prabhakarreddy1433;
GRANT ROLE IT_ROLE TO USER prabhakarreddy1433;


-- HR_ROLE
GRANT USAGE ON DATABASE MYSNOW TO ROLE HR_ROLE;
GRANT USAGE ON SCHEMA MYSNOW.public TO ROLE HR_ROLE;
GRANT SELECT ON TABLE employee_data TO ROLE HR_ROLE;

-- FINANCE_ROLE
GRANT USAGE ON DATABASE MYSNOW TO ROLE FINANCE_ROLE;
GRANT USAGE ON SCHEMA MYSNOW.public TO ROLE FINANCE_ROLE;
GRANT SELECT ON TABLE employee_data TO ROLE FINANCE_ROLE;

-- IT_ROLE
GRANT USAGE ON DATABASE MYSNOW TO ROLE IT_ROLE;
GRANT USAGE ON SCHEMA MYSNOW.public TO ROLE IT_ROLE;
GRANT SELECT ON TABLE employee_data TO ROLE IT_ROLE;


CREATE OR REPLACE ROW ACCESS POLICY row_policy_dept_filter
AS (dept STRING) RETURNS BOOLEAN ->
    CASE 
        WHEN CURRENT_ROLE() = 'ACCOUNTADMIN' THEN TRUE
        WHEN dept = 'HR' AND CURRENT_ROLE() = 'HR_ROLE' THEN TRUE
        WHEN dept = 'Finance' AND CURRENT_ROLE() = 'FINANCE_ROLE' THEN TRUE
        WHEN dept = 'IT' AND CURRENT_ROLE() = 'IT_ROLE' THEN TRUE
        ELSE FALSE
    END;

---Row access policy 'ROW_POLICY_DEPT_FILTER' is successfully created.

ALTER TABLE employee_data 
ADD ROW ACCESS POLICY row_policy_dept_filter ON (department);

USE ROLE ACCOUNTADMIN;
SELECT * FROM employee_data;

EMP_ID	FULL_NAME	DEPARTMENT	BIRTH_DATE	SALARY
101	Amit Sharma	HR	1990-07-15	50000
102	Priya Mehta	Finance	1985-12-03	75000
103	Ravi Kumar	IT	1992-03-22	90000

USE ROLE HR_ROLE;
SELECT * FROM employee_data;

EMP_ID	FULL_NAME	DEPARTMENT	BIRTH_DATE	SALARY
101	Amit Sharma	HR	1990-07-15	50000

USE ROLE FINANCE_ROLE;
SELECT * FROM employee_data;

EMP_ID	FULL_NAME	DEPARTMENT	BIRTH_DATE	SALARY
102	Priya Mehta	Finance	1985-12-03	75000

USE ROLE IT_ROLE;
SELECT * FROM employee_data;

EMP_ID	FULL_NAME	DEPARTMENT	BIRTH_DATE	SALARY
103	Ravi Kumar	IT	1992-03-22	90000



