CREATE TABLE TG_EMPL123
( EMPID INT,
  EMPNAME VARCHAR(30),
  SALARY FLOAT,
  AGE INT,
  DEPT VARCHAR(10),
  LOCATION VARCHAR(20)
);

CREATE STREAM STREAM_TG_EMPL123 ON TABLE TG_EMPL123;

SELECT * FROM STREAM_TG_EMPL123;

DROP TABLE TG_EMPL123;

SELECT * FROM STREAM_TG_EMPL123;

Base table 'MYSNOW.PUBLIC.TG_EMPL123' dropped, cannot read from stream 'STREAM_TG_EMPL123' in line 1 position 14.