
-- Step 1: Create the input table
CREATE OR REPLACE TABLE input_names (name STRING);

-- Step 2: Insert the data
INSERT INTO input_names (name)
VALUES 
    ('RAJESH KUMAR REDDY'),
    ('RAJESH'),
    ('APARNA PAUL'),
    ('KOTLA-ROJA-REDDY');


SELECT *FROM input_names;

NAME
RAJESH KUMAR REDDY
RAJESH
APARNA PAUL
KOTLA-ROJA-REDDY

Expected output :


NAME	COL1	COL2	COL3
RAJESH KUMAR REDDY	RAJESH	KUMAR	REDDY
RAJESH	RAJESH		
APARNA PAUL	APARNA	PAUL	
KOTLA-ROJA-REDDY	KOTLA	ROJA	REDDY

SELECT
    SPLIT_PART(name, ' ', 1) AS COL1,
    SPLIT_PART(name, ' ', 2) AS COL2,
    SPLIT_PART(name, ' ', 3) AS COL3
FROM input_names;

COL1	COL2	COL3
RAJESH	KUMAR	REDDY
RAJESH		
APARNA	PAUL	
KOTLA-ROJA-REDDY		

SELECT
    name,
    REGEXP_SUBSTR(name, '\\S+', 1, 1) AS COL1,
    REGEXP_SUBSTR(name, '\\S+', 1, 2) AS COL2,
    REGEXP_SUBSTR(name, '\\S+', 1, 3) AS COL3
FROM input_names;

NAME	COL1	COL2	COL3
RAJESH KUMAR REDDY	RAJESH	KUMAR	REDDY
RAJESH	RAJESH		
APARNA PAUL	APARNA	PAUL	
KOTLA-ROJA-REDDY	KOTLA-ROJA-REDDY		

SELECT
    name,
    REGEXP_SUBSTR(REPLACE(name, '-', ' '), '\\S+', 1, 1) AS COL1,
    REGEXP_SUBSTR(REPLACE(name, '-', ' '), '\\S+', 1, 2) AS COL2,
    REGEXP_SUBSTR(REPLACE(name, '-', ' '), '\\S+', 1, 3) AS COL3
FROM input_names;


SELECT
    name,
    SPLIT(REPLACE(name, '-', ' '), ' ')[0] AS COL1,
    SPLIT(REPLACE(name, '-', ' '), ' ')[1] AS COL2,
    SPLIT(REPLACE(name, '-', ' '), ' ')[2] AS COL3
FROM input_names;

SELECT
    name,
    SPLIT_PART(REPLACE(name, '-', ' '), ' ', 1) AS COL1,
    SPLIT_PART(REPLACE(name, '-', ' '), ' ', 2) AS COL2,
    SPLIT_PART(REPLACE(name, '-', ' '), ' ', 3) AS COL3
FROM input_names;


NAME	COL1	COL2	COL3
RAJESH KUMAR REDDY	RAJESH	KUMAR	REDDY
RAJESH	RAJESH		
APARNA PAUL	APARNA	PAUL	
KOTLA-ROJA-REDDY	KOTLA	ROJA	REDDY
