Write a SQL query to identify duplicate rows in the DEPTDUP table based on DEPTNO, DNAME, and LOC. The output should include a flag (Y/N) and the count of how many times each row appears.



DROP TABLE DEPTDUP;

CREATE TABLE DEPTDUP (
    DEPTNO INT,
    DNAME VARCHAR(50),
    LOC VARCHAR(50)
);


BEGIN
INSERT INTO DEPTDUP VALUES (10, 'ACCOUNTING', 'NEW YORK');
INSERT INTO DEPTDUP VALUES (10, 'ACCOUNTING', 'NEW YORK');
INSERT INTO DEPTDUP VALUES (20, 'RESEARCH', 'DALLAS');
INSERT INTO DEPTDUP VALUES (30, 'SALES', 'CHICAGO');
INSERT INTO DEPTDUP VALUES (40, 'OPERATIONS', 'BOSTON');
INSERT INTO DEPTDUP VALUES (20, 'RESEARCH', 'DALLAS');
INSERT INTO DEPTDUP VALUES (20, 'RESEARCH', 'DALLAS');
INSERT INTO DEPTDUP VALUES (20, 'RESEARCH', 'HYDERABAD');
INSERT INTO DEPTDUP VALUES (20, 'ACCOUNTS', 'SECBAD');
COMMIT;
END;

SELECT * FROM DEPTDUP;

SELECT DEPTNO,DNAME,LOC,COUNT(*)
FROM DEPTDUP
GROUP BY DEPTNO,DNAME,LOC
HAVING COUNT(*)>1
ORDER BY DEPTNO;

DEPTNO	DNAME	LOC	COUNT(*)
10	ACCOUNTING	NEW YORK	2
20	RESEARCH	DALLAS	    3


SELECT *
FROM (
    SELECT *,
           COUNT(*) OVER (PARTITION BY DEPTNO) AS DUP_COUNT
    FROM DEPTDUP
)
WHERE DUP_COUNT > 1;

DEPTNO	DNAME	LOC	DUP_COUNT
10	ACCOUNTING	NEW YORK	2
10	ACCOUNTING	NEW YORK	2
20	RESEARCH	DALLAS	5
20	RESEARCH	DALLAS	5
20	RESEARCH	DALLAS	5
20	RESEARCH	HYDERABAD	5
20	ACCOUNTS	SECBAD	5


SELECT *
FROM (
    SELECT *,
           COUNT(*) OVER (PARTITION BY DEPTNO, DNAME, LOC) AS DUP_COUNT
    FROM DEPTDUP
)
WHERE DUP_COUNT > 1;

DEPTNO	DNAME	LOC	DUP_COUNT
10	ACCOUNTING	NEW YORK	2
10	ACCOUNTING	NEW YORK	2
20	RESEARCH	DALLAS	3
20	RESEARCH	DALLAS	3
20	RESEARCH	DALLAS	3


SELECT *,
       CASE 
           WHEN COUNT(*) OVER (PARTITION BY DEPTNO, DNAME, LOC) > 1 THEN 'Y'
           ELSE 'N'
       END AS IS_DUPLICATE,
       COUNT(*) OVER (PARTITION BY DEPTNO, DNAME, LOC ) AS DUP_COUNT
FROM DEPTDUP
ORDER BY DEPTNO ASC;


DEPTNO	DNAME	LOC	IS_DUPLICATE	DUP_COUNT
10	ACCOUNTING	NEW YORK	Y	2
10	ACCOUNTING	NEW YORK	Y	2
20	RESEARCH	DALLAS	Y	3
20	RESEARCH	DALLAS	Y	3
20	RESEARCH	DALLAS	Y	3
20	RESEARCH	HYDERABAD	N	1
20	ACCOUNTS	SECBAD	N	1
30	SALES	CHICAGO	N	1
40	OPERATIONS	BOSTON	N	1
