Top 3 Salaried Employees per Department


SELECT *FROM EMP;

SELECT *FROM(
SELECT EMPNO,ENAME,JOB,SAL,DEPTNO,
DENSE_RANK() OVER(PARTITION BY DEPTNO ORDER BY SAL DESC) RANK
FROM EMP)E
WHERE E.RANK<=3;

SELECT EMPNO,ENAME,JOB,SAL,DEPTNO,
DENSE_RANK() OVER(PARTITION BY DEPTNO ORDER BY SAL DESC) DRANK
FROM EMP
QUALIFY DRANK<=3

SELECT EMPNO,ENAME,JOB,SAL,DEPTNO
FROM EMP
QUALIFY DENSE_RANK() OVER(PARTITION BY DEPTNO ORDER BY SAL DESC)<=3

WITH DENSE_RANK AS(
SELECT EMPNO,ENAME,JOB,SAL,DEPTNO,
DENSE_RANK() OVER(PARTITION BY DEPTNO ORDER BY SAL DESC) DRANK
FROM EMP)
SELECT *FROM DENSE_RANK WHERE DRANK<=3

