SELECT * FROM INFORMATION_SCHEMA.VIEWS
WHERE TABLE_NAME IN('TABLES',
'COLUMNS',
'ELEMENT_TYPES',
'FIELDS',
'SCHEMATA',
'SEQUENCES',
'VIEWS',
'TABLE_PRIVILEGES',
'USAGE_PRIVILEGES',
'DATABASES',
'REPLICATION_DATABASES',
'REPLICATION_GROUPS',
'FUNCTIONS',
'PROCEDURES',
'OBJECT_PRIVILEGES',
'FILE_FORMATS',
'APPLICABLE_ROLES',
'ENABLED_ROLES',
'STAGES',
'REFERENTIAL_CONSTRAINTS',
'TABLE_CONSTRAINTS',
'CLASS_INSTANCES',
'CLASSES',
'CLASS_INSTANCE_FUNCTIONS',
'CLASS_INSTANCE_PROCEDURES',
'MODEL_VERSIONS',
'INFORMATION_SCHEMA_CATALOG_NAME',
'LOAD_HISTORY',
'SNAPSHOT_POLICIES',
'SNAPSHOT_SETS',
'SNAPSHOTS',
'TABLE_STORAGE_METRICS',
'PIPES','EXTERNAL_TABLES',
'EVENT_TABLES',
'PACKAGES',
'CURRENT_PACKAGES_POLICY',
'STREAMLITS',
'NOTEBOOKS',
'HYBRID_TABLES',
'INDEXES',
'INDEX_COLUMNS',
'SERVICES',
'GIT_REPOSITORIES',
'CORTEX_SEARCH_SERVICES',
'SEMANTIC_VIEWS',
'SEMANTIC_TABLES',
'SEMANTIC_RELATIONSHIPS',
'SEMANTIC_FACTS',
'SEMANTIC_DIMENSIONS',
'SEMANTIC_METRICS',
'CORTEX_SEARCH_SERVICE_SCORING_PROFILES',
'APPLICATION_SPECIFICATIONS')
AND TABLE_SCHEMA='INFORMATION_SCHEMA';



*************************************************************************


SELECT *FROM INFORMATION_SCHEMA.TABLES
SELECT *FROM INFORMATION_SCHEMA.COLUMNS
SELECT *FROM INFORMATION_SCHEMA.ELEMENT_TYPES
SELECT *FROM INFORMATION_SCHEMA.FIELDS
SELECT *FROM INFORMATION_SCHEMA.SCHEMATA
SELECT *FROM INFORMATION_SCHEMA.SEQUENCES
SELECT *FROM INFORMATION_SCHEMA.VIEWS
SELECT *FROM INFORMATION_SCHEMA.TABLE_PRIVILEGES
SELECT *FROM INFORMATION_SCHEMA.USAGE_PRIVILEGES
SELECT *FROM INFORMATION_SCHEMA.DATABASES 
SELECT *FROM INFORMATION_SCHEMA.REPLICATION_DATABASES
SELECT *FROM INFORMATION_SCHEMA.REPLICATION_GROUPS
SELECT *FROM INFORMATION_SCHEMA.FUNCTIONS
SELECT *FROM INFORMATION_SCHEMA.PROCEDURES
SELECT *FROM INFORMATION_SCHEMA.OBJECT_PRIVILEGES LIMIT 1
SELECT *FROM INFORMATION_SCHEMA.FILE_FORMATS
SELECT *FROM INFORMATION_SCHEMA.APPLICABLE_ROLES
SELECT *FROM INFORMATION_SCHEMA.ENABLED_ROLES
SELECT *FROM INFORMATION_SCHEMA.STAGES
SELECT *FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS
SELECT *FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
SELECT *FROM INFORMATION_SCHEMA.CLASS_INSTANCES
SELECT *FROM INFORMATION_SCHEMA.CLASSES
SELECT *FROM INFORMATION_SCHEMA.CLASS_INSTANCE_FUNCTIONS
SELECT *FROM INFORMATION_SCHEMA.CLASS_INSTANCE_PROCEDURES
SELECT *FROM INFORMATION_SCHEMA.MODEL_VERSIONS
SELECT *FROM INFORMATION_SCHEMA.INFORMATION_SCHEMA_CATALOG_NAME
SELECT *FROM INFORMATION_SCHEMA.LOAD_HISTORY
SELECT *FROM INFORMATION_SCHEMA.SNAPSHOT_POLICIES
SELECT *FROM INFORMATION_SCHEMA.SNAPSHOT_SETS
SELECT *FROM INFORMATION_SCHEMA.SNAPSHOTS
SELECT *FROM INFORMATION_SCHEMA.TABLE_STORAGE_METRICS
SELECT *FROM INFORMATION_SCHEMA.PIPES
SELECT *FROM INFORMATION_SCHEMA.EXTERNAL_TABLES
SELECT *FROM INFORMATION_SCHEMA.EVENT_TABLES
SELECT *FROM INFORMATION_SCHEMA.PACKAGES
SELECT *FROM INFORMATION_SCHEMA.CURRENT_PACKAGES_POLICY
SELECT *FROM INFORMATION_SCHEMA.STREAMLITS
SELECT *FROM INFORMATION_SCHEMA.NOTEBOOKS
SELECT *FROM INFORMATION_SCHEMA.HYBRID_TABLES
SELECT *FROM INFORMATION_SCHEMA.INDEXES
SELECT *FROM INFORMATION_SCHEMA.INDEX_COLUMNS
SELECT *FROM INFORMATION_SCHEMA.SERVICES
SELECT *FROM INFORMATION_SCHEMA.GIT_REPOSITORIES
SELECT *FROM INFORMATION_SCHEMA.CORTEX_SEARCH_SERVICES
SELECT *FROM INFORMATION_SCHEMA.SEMANTIC_VIEWS
SELECT *FROM INFORMATION_SCHEMA.SEMANTIC_TABLES
SELECT *FROM INFORMATION_SCHEMA.SEMANTIC_RELATIONSHIPS
SELECT *FROM INFORMATION_SCHEMA.SEMANTIC_FACTS
SELECT *FROM INFORMATION_SCHEMA.SEMANTIC_DIMENSIONS
SELECT *FROM INFORMATION_SCHEMA.SEMANTIC_METRICS
SELECT *FROM INFORMATION_SCHEMA.CORTEX_SEARCH_SERVICE_SCORING_PROFILES
SELECT *FROM INFORMATION_SCHEMA.APPLICATION_SPECIFICATIONS