

SELECT * FROM EMP;

SELECT * FROM DEPT;

SELECT *FROM(
SELECT EMPNO,ENAME,JOB,SAL,E.DEPTNO,DNAME,LOC,
DENSE_RANK() OVER(PARTITION BY E.DEPTNO ORDER BY SAL DESC) DRANK
FROM EMP E,DEPT D
WHERE E.DEPTNO=D.DEPTNO)ED
WHERE ED.DRANK<=3;

***********************************************************************************************************
WITH Ranked_Employees AS (
    SELECT 
        E.EMPNO,
        E.ENAME,
        E.JOB,
        E.SAL,
        E.DEPTNO,
        D.DNAME,
        D.LOC,
        DENSE_RANK() OVER(PARTITION BY E.DEPTNO ORDER BY E.SAL DESC) AS DRANK
    FROM EMP E
    JOIN DEPT D ON E.DEPTNO = D.DEPTNO
)
SELECT *
FROM Ranked_Employees
WHERE DRANK <= 3;

*********************************************************************************************************
WITH RANKED_EMPLOYEES AS (
  SELECT EMPNO, ENAME, JOB, SAL, E.DEPTNO, DNAME, LOC,
         DENSE_RANK() OVER(PARTITION BY E.DEPTNO ORDER BY SAL DESC) AS DRANK
  FROM EMP E
  JOIN DEPT D ON E.DEPTNO = D.DEPTNO
),
DEPT_TOTAL AS (
  SELECT DEPTNO, SUM(SAL) AS TOTAL_SAL
  FROM EMP
  GROUP BY DEPTNO
)
SELECT R.*, D.TOTAL_SAL
FROM RANKED_EMPLOYEES R
JOIN DEPT_TOTAL D ON R.DEPTNO = D.DEPTNO
WHERE DRANK <= 3;

*******************************************************************************

WITH RANKED_EMPLOYEES AS (
  SELECT EMPNO, ENAME, JOB, SAL, E.DEPTNO, DNAME, LOC,
         DENSE_RANK() OVER(PARTITION BY E.DEPTNO ORDER BY SAL DESC) AS DRANK
  FROM EMP E
  JOIN DEPT D ON E.DEPTNO = D.DEPTNO
),

DEPT_TOTAL AS (
  SELECT DEPTNO, SUM(SAL) AS TOTAL_SAL
  FROM EMP
  GROUP BY DEPTNO
),

DEPT_AVG AS (
  SELECT DEPTNO, AVG(SAL) AS AVG_SAL
  FROM EMP
  GROUP BY DEPTNO
),

DEPT_COUNT AS (
  SELECT DEPTNO, COUNT(*) AS EMP_COUNT
  FROM EMP
  GROUP BY DEPTNO
),

TOP_SALARY AS (
  SELECT DEPTNO, MAX(SAL) AS MAX_SAL
  FROM EMP
  GROUP BY DEPTNO
)

SELECT 
  R.EMPNO, R.ENAME, R.JOB, R.SAL, R.DEPTNO, R.DNAME, R.LOC,
  D.TOTAL_SAL,
  A.AVG_SAL,
  C.EMP_COUNT,
  T.MAX_SAL - R.SAL AS SAL_DIFF_FROM_TOP
FROM RANKED_EMPLOYEES R
JOIN DEPT_TOTAL D ON R.DEPTNO = D.DEPTNO
JOIN DEPT_AVG A ON R.DEPTNO = A.DEPTNO
JOIN DEPT_COUNT C ON R.DEPTNO = C.DEPTNO
JOIN TOP_SALARY T ON R.DEPTNO = T.DEPTNO
WHERE R.DRANK <= 3;

*****************************************************************************************
WITH RANKED_EMPLOYEES AS (
  SELECT EMPNO, ENAME, JOB, SAL, E.DEPTNO, DNAME, LOC,
         DENSE_RANK() OVER(PARTITION BY E.DEPTNO ORDER BY SAL DESC) AS DRANK
  FROM EMP E
  JOIN DEPT D ON E.DEPTNO = D.DEPTNO
),

DEPT_TOTAL AS (
  SELECT DEPTNO, SUM(SAL) AS TOTAL_SAL
  FROM EMP
  GROUP BY DEPTNO
),

DEPT_AVG AS (
  SELECT DEPTNO, AVG(SAL) AS AVG_SAL
  FROM EMP
  GROUP BY DEPTNO
),

DEPT_COUNT AS (
  SELECT DEPTNO, COUNT(*) AS EMP_COUNT
  FROM EMP
  GROUP BY DEPTNO
),

TOP_SALARY AS (
  SELECT DEPTNO, MAX(SAL) AS MAX_SAL
  FROM EMP
  GROUP BY DEPTNO
),

DEPT_MIN_SAL AS (
  SELECT DEPTNO, MIN(SAL) AS MIN_SAL
  FROM EMP
  GROUP BY DEPTNO
),

DEPT_JOB_COUNT AS (
  SELECT DEPTNO, COUNT(DISTINCT JOB) AS JOB_VARIETY
  FROM EMP
  GROUP BY DEPTNO
)

SELECT 
  R.EMPNO, R.ENAME, R.JOB, R.SAL, R.DEPTNO, R.DNAME, R.LOC,
  D.TOTAL_SAL,
  A.AVG_SAL,
  C.EMP_COUNT,
  T.MAX_SAL - R.SAL AS SAL_DIFF_FROM_TOP,
  M.MIN_SAL,
  J.JOB_VARIETY
FROM RANKED_EMPLOYEES R
LEFT JOIN DEPT_TOTAL D ON R.DEPTNO = D.DEPTNO
LEFT JOIN DEPT_AVG A ON R.DEPTNO = A.DEPTNO
LEFT JOIN DEPT_COUNT C ON R.DEPTNO = C.DEPTNO
LEFT JOIN TOP_SALARY T ON R.DEPTNO = T.DEPTNO
LEFT JOIN DEPT_MIN_SAL M ON R.DEPTNO = M.DEPTNO
LEFT JOIN DEPT_JOB_COUNT J ON R.DEPTNO = J.DEPTNO
WHERE R.DRANK <= 3;
