-- Step 1: Create the DEPTDUP table
DROP TABLE DEPTDUP;

CREATE TABLE DEPTDUP (
    DEPTNO INT,
    DNAME VARCHAR(50),
    LOC VARCHAR(50)
);


BEGIN
INSERT INTO DEPTDUP VALUES (10, 'ACCOUNTING', 'NEW YORK');
INSERT INTO DEPTDUP VALUES (10, 'ACCOUNTING', 'NEW YORK');
INSERT INTO DEPTDUP VALUES (20, 'RESEARCH', 'DALLAS');
INSERT INTO DEPTDUP VALUES (30, 'SALES', 'CHICAGO');
INSERT INTO DEPTDUP VALUES (40, 'OPERATIONS', 'BOSTON');
INSERT INTO DEPTDUP VALUES (20, 'RESEARCH', 'DALLAS');
INSERT INTO DEPTDUP VALUES (20, 'RESEARCH', 'DALLAS');
COMMIT;
END;

SELECT * FROM DEPTDUP;
    
DELETE FROM DEPTDUP WHERE ROWID IN(
SELECT ROWID FROM(
SELECT ROWID RID,DEPTNO,DNAME,LOC,
ROW_NUMBER() OVER(PARTITION BY DEPTNO ORDER BY DEPTNO) RN
FROM DEPTDUP)E
WHERE E.RN>1);

SELECT * FROM DEPTDUP;

DELETE FROM DEPTDUP D
WHERE EXISTS (
  SELECT 1 FROM DEPTDUP
  WHERE DEPTNO = D.DEPTNO
    AND DNAME = D.DNAME
    AND LOC = D.LOC
    AND ROWID < D.ROWID
);


DELETE FROM DEPTDUP D
WHERE EXISTS (
  SELECT 1 FROM DEPTDUP
  WHERE DEPTNO = D.DEPTNO
    AND DNAME = D.DNAME
    AND LOC = D.LOC
    AND ROWID > D.ROWID
);



SELECT * FROM DEPTDUP;

DEPTNO	DNAME	LOC
10	ACCOUNTING	NEW YORK
20	RESEARCH	DALLAS
30	SALES	CHICAGO
40	OPERATIONS	BOSTON

4 rows selected.



DELETE FROM DEPTDUP WHERE ROWID NOT IN(SELECT MIN(ROWID) FROM DEPTDUP GROUP BY DEPTNO);
DELETE FROM DEPTDUP WHERE ROWID NOT IN(SELECT MAX(ROWID) FROM DEPTDUP GROUP BY DEPTNO);

Correct method:

DELETE FROM DEPTDUP
WHERE ROWID NOT IN (SELECT MIN(ROWID) FROM DEPTDUP GROUP BY DEPTNO, DNAME, LOC);

DELETE FROM DEPTDUP
WHERE ROWID NOT IN (SELECT MAX(ROWID) FROM DEPTDUP GROUP BY DEPTNO, DNAME, LOC);

*************************************
DELETE FROM DEPTDUP D1 WHERE ROWID>(SELECT MIN(ROWID) FROM DEPTDUP D2 WHERE D1.DEPTNO=D2.DEPTNO);

DELETE FROM DEPTDUP D1 WHERE ROWID<(SELECT MAX(ROWID) FROM DEPTDUP D2 WHERE D1.DEPTNO=D2.DEPTNO);


Correct method:

DELETE FROM DEPTDUP D1 
WHERE ROWID > ( SELECT MIN(D2.ROWID) FROM DEPTDUP D2 
  WHERE D1.DEPTNO = D2.DEPTNO 
    AND D1.DNAME = D2.DNAME 
    AND D1.LOC = D2.LOC
);


DELETE FROM DEPTDUP D1 
WHERE ROWID < ( SELECT MAX(D2.ROWID) FROM DEPTDUP D2 
  WHERE D1.DEPTNO = D2.DEPTNO 
    AND D1.DNAME = D2.DNAME 
    AND D1.LOC = D2.LOC
);


DELETE DEPTDUP WHERE ROWID NOT IN(SELECT ROWID
FROM DEPTDUP D
WHERE ROWID = (
    SELECT MIN(ROWID)
    FROM DEPTDUP
    WHERE DEPTNO = D.DEPTNO
      AND DNAME = D.DNAME
      AND LOC = D.LOC
));


DELETE DEPTDUP WHERE ROWID NOT IN(SELECT ROWID
FROM DEPTDUP D
WHERE ROWID = (
    SELECT MAX(ROWID)
    FROM DEPTDUP
    WHERE DEPTNO = D.DEPTNO
      AND DNAME = D.DNAME
      AND LOC = D.LOC
));