Add COPY INTO SQL (outside Python)


-- Create structured tables
CREATE OR REPLACE TABLE EMPLOYEES_STAGE (
  EMP_ID STRING,
  NAME STRING,
  DEPT_ID STRING,
  SALARY STRING
);

CREATE OR REPLACE TABLE DEPARTMENTS_STAGE (
  DEPT_ID STRING,
  DEPT_NAME STRING
);

-- Load CSVs using COPY INTO
COPY INTO EMPLOYEES_STAGE
FROM @my_stage/employees_test.csv
FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1);

COPY INTO DEPARTMENTS_STAGE
FROM @my_stage/departments_test.csv
FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1);


Optional: Automate with Snowpipe

-- Create Snowpipe for employees
CREATE OR REPLACE PIPE EMPLOYEES_PIPE AS
COPY INTO EMPLOYEES_STAGE
FROM @my_stage/employees_test.csv
FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1);

-- Create Snowpipe for departments
CREATE OR REPLACE PIPE DEPARTMENTS_PIPE AS
COPY INTO DEPARTMENTS_STAGE
FROM @my_stage/departments_test.csv
FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1);
